server:
  port: 18081
spring:
  datasource:
    url: jdbc:mysql://localhost/heima36?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

#配置Mybatis
#-别名包扫描
#mybatis.type-aliases-package=com.itheima.integration.domain
#-映射文件加载
#mybatis.mapper-locations=classpath:/mapper/*.xml

#配置日志输出-主要是输出sql语句
#logging.level.com.itheima.integration.mapper=debug
mybatis:
  type-aliases-package: com.itcast.pojo
  mapper-locations: classpath:com.itcast.*.xml
